# Generated by Django 6.1 on 2026-09-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_user_remove_appointment_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
    ]
