from django.urls import path
from . import views

urlpatterns = [
    # Public Pages
    path('', views.index, name='index'),
    path('index/', views.index, name='index_alt'),
    path('index.html', views.index),
    path('about/', views.about, name='about'),
    path('about.html', views.about),
    path('doctors/', views.doctors, name='doctors'),
    path('doctors.html', views.doctors),
    path('doctor-details/', views.doctor_details, name='doctor_details'),
    path('doctor-details.html', views.doctor_details),
    path('departments/', views.departments, name='departments'),
    path('departments.html', views.departments),
    path('contact/', views.contact, name='contact'),
    path('contact.html', views.contact),
    path('login/', views.login_view, name='login'),
    path('login.html', views.login_view),
    path('register/', views.register_view, name='register'),
    path('register.html', views.register_view),

    # Admin Portal Pages
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/dashboard.html', views.admin_dashboard),
    path('admin/appointments/', views.admin_appointments, name='admin_appointments'),
    path('admin/appointments.html', views.admin_appointments),
    path('admin/doctors/', views.admin_doctors, name='admin_doctors'),
    path('admin/doctors.html', views.admin_doctors),
    path('admin/patients/', views.admin_patients, name='admin_patients'),
    path('admin/patients.html', views.admin_patients),
    path('admin/departments/', views.admin_departments, name='admin_departments'),
    path('admin/departments.html', views.admin_departments),
    path('admin/reports/', views.admin_reports, name='admin_reports'),
    path('admin/reports.html', views.admin_reports),
    path('admin/settings/', views.admin_settings, name='admin_settings'),
    path('admin/settings.html', views.admin_settings),

    # Doctor Portal Pages
    path('doctor/dashboard/', views.doctor_dashboard, name='doctor_dashboard'),
    path('doctor/dashboard.html', views.doctor_dashboard),
    path('doctor/appointments/', views.doctor_appointments, name='doctor_appointments'),
    path('doctor/appointments.html', views.doctor_appointments),
    path('doctor/patients/', views.doctor_patients, name='doctor_patients'),
    path('doctor/patients.html', views.doctor_patients),
    path('doctor/patient-details/', views.doctor_patient_details, name='doctor_patient_details'),
    path('doctor/patient-details.html', views.doctor_patient_details),
    path('doctor/prescriptions/', views.doctor_prescriptions, name='doctor_prescriptions'),
    path('doctor/prescriptions.html', views.doctor_prescriptions),
    path('doctor/medical-records/', views.doctor_medical_records, name='doctor_medical_records'),
    path('doctor/medical-records.html', views.doctor_medical_records),
    path('doctor/profile/', views.doctor_profile, name='doctor_profile'),
    path('doctor/profile.html', views.doctor_profile),

    # Patient Portal Pages
    path('patient/dashboard/', views.patient_dashboard, name='patient_dashboard'),
    path('patient/dashboard.html', views.patient_dashboard),
    path('patient/book-appointment/', views.patient_book_appointment, name='patient_book_appointment'),
    path('patient/book-appointment.html', views.patient_book_appointment),
    path('patient/appointments/', views.patient_appointments, name='patient_appointments'),
    path('patient/appointments.html', views.patient_appointments),
    path('patient/doctors/', views.patient_doctors, name='patient_doctors'),
    path('patient/doctors.html', views.patient_doctors),
    path('patient/medical-history/', views.patient_medical_history, name='patient_medical_history'),
    path('patient/medical-history.html', views.patient_medical_history),
    path('patient/prescriptions/', views.patient_prescriptions, name='patient_prescriptions'),
    path('patient/prescriptions.html', views.patient_prescriptions),
    path('patient/profile/', views.patient_profile, name='patient_profile'),
    path('patient/profile.html', views.patient_profile),
]
